import type { ThemeConfig } from 'antd';

const theme: ThemeConfig = {
  token: {
    colorPrimary: '#000000',
    colorBgContainer: '#ffffff',
    colorText: '#000000',
    colorTextSecondary: '#4b5563',
    colorBorder: '#d1d5db',
    colorBgElevated: '#ffffff',
    borderRadius: 6,
    colorLink: '#000000',
    colorLinkHover: '#4b5563',
    colorSuccess: '#059669',
    colorWarning: '#d97706',
    colorError: '#dc2626',
    colorInfo: '#0284c7',
    fontSize: 14,
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
  },
  components: {
    Select: {
      colorBgContainer: '#ffffff',
      colorText: '#000000',
      colorTextPlaceholder: '#9ca3af',
      colorBorder: '#d1d5db',
      controlOutline: 'rgba(0, 0, 0, 0.1)',
      optionSelectedBg: '#f3f4f6',
      optionActiveBg: '#f9fafb',
      colorBgElevated: '#ffffff',
      colorTextQuaternary: '#6b7280',
      multipleItemBg: '#f3f4f6',
      multipleItemBorderColor: '#e5e7eb',
    },
    Input: {
      colorBgContainer: '#ffffff',
      colorText: '#000000',
      colorTextPlaceholder: '#9ca3af',
      colorBorder: '#d1d5db',
      activeBorderColor: '#000000',
      hoverBorderColor: '#6b7280',
    },
    Button: {
      colorPrimary: '#000000',
      colorPrimaryHover: '#374151',
      colorPrimaryActive: '#1f2937',
      primaryColor: '#ffffff',
      defaultBorderColor: '#d1d5db',
      defaultColor: '#000000',
      defaultBg: '#ffffff',
    },
    Table: {
      colorBgContainer: '#ffffff',
      headerBg: '#f9fafb',
      headerColor: '#111827',
      colorText: '#000000',
      borderColor: '#e5e7eb',
      rowHoverBg: '#f9fafb',
      headerSplitColor: '#e5e7eb',
    },
    Modal: {
      contentBg: '#ffffff',
      headerBg: '#ffffff',
      titleColor: '#000000',
      colorText: '#000000',
      colorIcon: '#6b7280',
      colorIconHover: '#000000',
    },
    Card: {
      colorBgContainer: '#ffffff',
      colorBorderSecondary: '#e5e7eb',
      colorText: '#000000',
      colorTextHeading: '#000000',
    },
    Tag: {
      defaultBg: '#f3f4f6',
      defaultColor: '#374151',
    },
    Badge: {
      colorBgContainer: '#000000',
      colorPrimary: '#000000',
      colorError: '#dc2626',
      colorSuccess: '#059669',
    },
    Dropdown: {
      colorBgElevated: '#ffffff',
      colorText: '#000000',
      controlItemBgHover: '#f3f4f6',
      controlItemBgActive: '#e5e7eb',
      colorPrimary: '#000000',
    },
    DatePicker: {
      colorBgContainer: '#ffffff',
      colorBgElevated: '#ffffff',
      colorText: '#000000',
      colorTextPlaceholder: '#9ca3af',
      colorBorder: '#d1d5db',
      cellActiveWithRangeBg: '#f3f4f6',
      cellHoverBg: '#f9fafb',
      cellBgDisabled: '#f9fafb',
      colorTextDisabled: '#d1d5db',
    },
    TimePicker: {
      colorBgContainer: '#ffffff',
      colorBgElevated: '#ffffff',
      colorText: '#000000',
      colorTextPlaceholder: '#9ca3af',
      colorBorder: '#d1d5db',
      cellHoverBg: '#f9fafb',
    },
    Form: {
      labelColor: '#374151',
      colorError: '#dc2626',
    },
    Tabs: {
      colorText: '#6b7280',
      itemSelectedColor: '#000000',
      itemHoverColor: '#374151',
      itemActiveColor: '#000000',
      inkBarColor: '#000000',
      colorBorderSecondary: '#e5e7eb',
      cardBg: '#f9fafb',
    },
    Tooltip: {
      colorBgSpotlight: 'rgba(0, 0, 0, 0.85)',
      colorTextLightSolid: '#ffffff',
    },
    Popover: {
      colorBgElevated: '#ffffff',
      colorText: '#000000',
    },
    Checkbox: {
      colorPrimary: '#000000',
      colorPrimaryHover: '#374151',
      colorBorder: '#d1d5db',
      colorBgContainer: '#ffffff',
    },
    Radio: {
      colorPrimary: '#000000',
      colorPrimaryHover: '#374151',
      colorBorder: '#d1d5db',
      buttonSolidCheckedBg: '#000000',
      buttonSolidCheckedHoverBg: '#374151',
    },
    Switch: {
      colorPrimary: '#000000',
      colorPrimaryHover: '#374151',
      colorTextQuaternary: '#d1d5db',
    },
    Steps: {
      colorPrimary: '#000000',
      colorText: '#6b7280',
      colorTextDescription: '#9ca3af',
      colorSplit: '#e5e7eb',
      colorBorderSecondary: '#e5e7eb',
      dotCurrentSize: 8,
      dotSize: 8,
    },
  },
};

export default theme;